server:
  port: 8094 # Using Alert service port as base

spring:
  application:
    name: platform-service
  datasource:
    url: jdbc:postgresql://localhost:5432/platform_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: platform-service-group-v4
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "com.ticketkatum.events.*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

# OpenAI Key should be env var
spring.ai.openai.api-key: ${OPENAI_API_KEY}
