apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: ticket-katum
spec:
  selector:
    app: event-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
