apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: ticket-katum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: image-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761/eureka/"
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: cloud-name
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-key
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
