apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service
  namespace: ticket-katum
  labels:
    app: market-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-service
  template:
    metadata:
      labels:
        app: market-service
    spec:
      containers:
      - name: market-service
        image: market-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8092
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: EUREKA_SERVER_URL
          value: "http://eureka-server:8761/eureka/"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: market-db-secret
              key: url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: market-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: market-db-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8092
          initialDelaySeconds: 180
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8092
          initialDelaySeconds: 180
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: market-service
  namespace: ticket-katum
spec:
  selector:
    app: market-service
  ports:
    - port: 8092
      targetPort: 8092
      name: http
