apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services/payment-service-deployment.yaml
  - services/hotel-service-deployment.yaml
  - services/bus-service-deployment.yaml
  - services/market-service-deployment.yaml
  - services/eureka-deployment.yaml
  - services/web-bff-deployment.yaml
  - services/booking-service-deployment.yaml
  - services/configmaps.yaml
  - services/secrets.yaml
  - services/auth-service-deployment.yaml
  - services/ingress.yaml
  - services/persistent-volumes.yaml
  - services/manual-pvs.yaml
  - services/prometheus-config.yaml
  - services/statefulsets.yaml

