apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZmUxL3owenROU1V3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1UWXhOak00TkRkYUZ3MHpOVEV5TVRReE5qUXpORGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNyTXkzaHp5b3Y0VjU5QWtPM1NiSkl1UVZtdnI0QXQ1a0o0MG11Rmg5OEV0Z1NJU1RwdDVkQ0pOekkKQlJtWE1kQ0NwRTV1NG43RmpVUG9IWDY4NStOa1VuSTc2Y09ua0ZCSm9wNnNvcHdZRHV2djE5K0FvcTRIbjJ0TApyTXRZei95YjVoQTZpejlOS2VJVmZyUFovZ1ZXcmVvZVJDRDBlM0tsQVFhZ09pTVZrTTZZT2pKRnZTUDJOUnFnCkdtYThPcmo4SWplREhnL2ZQVGVubVhpQUhZTU01UXJ1bDRMajgxRXJPQm02MHI1Tm9uTHZTNW1rWGVMVTczNlQKSWwxWjJYUTJubVovWEhBMjlkU0paNy9OSzVlb1dUbG9TSzZNYTNBcThmTm5jdXVQT1MwZVNqSWRWbnF4YnZjTwp6aDIrbERWZ2cxZDVMZjVDU2xELzBmbHJLZnl4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRS1FMK2JOQy94R25Ud2xyZnJjQVV2T2syeGl6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnR6eEg5dmt2cwpiemE2dXpUVWRKcm5rWmhJOGIwOEh5cEtYVitXaGpzdUNNRE45Q1pMZW8ydTc4Q241cVNTczJKKzZyODJnYUUwCjJid213R2psaTlNeGVZSWIyMUhodHM1Z3FNaUc0R09GYWc1cWJlT2h3MElUV2lsbEswZEtZZUVRR2U4MjlpYU0KUXJ1UXZrWjRqMkJaS0xpb0RHTHI3QVBRd0pNM2xISW5CdS9kbmEveGZGbWk2clhOSDdOMEltNG8xcCtRRFVXNApPL0ZNaTJRaHk0cnpiWjNQNks5VGtoVWc3ZDd3ZnBhRzZVd0drSXFEWVIwMkJxeVVJT0dkazBVanJsNjl4UWMwCi8zSVRITG14S05vRCtrWHJ0Wkhob3N2emJMMTh4QjRMMXFOUWY1SU0yTTFFMGdFWEg5NERjbnNVVk1FL0RhdjgKTzlUeTJPcnZsYXNICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://2946F4205ECC22B988B4EB6C25289A7B.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:572638914672:cluster/ticket-katum-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:572638914672:cluster/ticket-katum-cluster
    namespace: ticket-katum
    user: arn:aws:eks:us-east-1:572638914672:cluster/ticket-katum-cluster
  name: arn:aws:eks:us-east-1:572638914672:cluster/ticket-katum-cluster
current-context: arn:aws:eks:us-east-1:572638914672:cluster/ticket-katum-cluster
kind: Config
users:
- name: arn:aws:eks:us-east-1:572638914672:cluster/ticket-katum-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - ticket-katum-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
