import React, { useState, useEffect } from 'react';
import { toast } from 'react-toastify';
import ApiService from '../../services/api.service';
import API_CONFIG from '../../config/api';
import { useNavigate } from 'react-router-dom';
import { DataTable } from './DataTable';
import { BusSeatPreview } from './BusSeatPreview';

export function BusManager() {
    const navigate = useNavigate();
    const today = new Date().toISOString().split("T")[0];

    // Tab state
    const [activeTab, setActiveTab] = useState('list');

    // Bus form state
    const [busName, setBusName] = useState("");
    const [busType, setBusType] = useState("DELUXE");
    const [busRoute, setBusRoute] = useState("");
    const [busDate, setBusDate] = useState("");
    const [allRoutes, setAllRoutes] = useState([]);
    const [basePrice, setBasePrice] = useState("");
    const [maxPrice, setMaxPrice] = useState("");
    const [busTime, setBusTime] = useState("");
    const [totalSeats, setTotalSeats] = useState("");
    const [isCreatingBus, setIsCreatingBus] = useState(false);

    // Seat form state
    const [seatNumber, setSeatNumber] = useState("");
    const [seatBusId, setSeatBusId] = useState("");
    const [seatPrice, setSeatPrice] = useState("");
    const [isReserved, setIsReserved] = useState(false);
    const [isCreatingSeat, setIsCreatingSeat] = useState(false);
    const [allBuses, setAllBuses] = useState([]);

    // Filter state
    const [statusFilter, setStatusFilter] = useState('all');
    const [dateFilter, setDateFilter] = useState('');
    const [viewMode, setViewMode] = useState('table'); // table or grid

    // Selected bus for seat preview
    const [selectedBusForPreview, setSelectedBusForPreview] = useState(null);
    const [isLoadingDetails, setIsLoadingDetails] = useState(false);
    const [busDetailsCache, setBusDetailsCache] = useState(new Map());

    useEffect(() => {
        getAllRoutes();
        getAllBuses();
    }, []);

    async function getAllRoutes() {
        const allroutesRes = await ApiService.get(API_CONFIG.ENDPOINTS.GET_ROUTES);
        if (allroutesRes) {
            const allRoutesLoad = await allroutesRes.data;
            setAllRoutes(allRoutesLoad);
        }
    }

    async function getAllBuses() {
        const allBusesRes = await ApiService.get(API_CONFIG.ENDPOINTS.GET_ALL_BUSES);
        if (allBusesRes) {
            const allBusesLoad = await allBusesRes.data;
            setAllBuses(allBusesLoad);
        }
    }

    async function handleViewSeats(bus) {
        setSelectedBusForPreview(bus); // Show modal immediately with partial data

        // Check cache first
        if (busDetailsCache.has(bus.id)) {
            console.log('Using cached bus details for bus', bus.id);
            setSelectedBusForPreview(busDetailsCache.get(bus.id));
            return;
        }

        setIsLoadingDetails(true);
        try {
            const res = await ApiService.get(`${API_CONFIG.ENDPOINTS.BUS_COMPLETE_DETAILS}${bus.id}/complete`);
            if (res && res.data) {
                const completeData = res.data;
                setSelectedBusForPreview(completeData);
                // Cache the complete data
                setBusDetailsCache(prev => new Map(prev).set(bus.id, completeData));
            }
        } catch (error) {
            console.error("Error fetching complete bus details:", error);
            toast.error("Failed to load latest seat availability");
        } finally {
            setIsLoadingDetails(false);
        }
    }

    async function createNewBus() {
        if (!busName || !busRoute || !busDate || !maxPrice || !basePrice || !busTime || !totalSeats) {
            toast.error("All fields are required!");
            return;
        }
        setIsCreatingBus(true);
        try {
            const payload = {
                busDto: {
                    busName,
                    busType,
                    departureDateTime: `${busDate}T${busTime}`,
                    date: busDate,
                    maxPrice,
                    basePrice,
                    seats: [], // Empty list as seats are generated by number
                    routeDto: null // Route is passed via routeId
                },
                routeId: parseInt(busRoute), // FIX: Use busRoute instead of undefined routeId
                numberOfSeats: parseInt(totalSeats)
            };

            // FIX: Use the routeId from the payload, not undefined variable
            const busRouteRes = await ApiService.post(`${API_CONFIG.ENDPOINTS.CREATE_BUS}/${payload.routeId}/buses`, payload);

            if (busRouteRes) {
                toast.success("New Bus created!");
                setBusName("");
                setBusType("DELUXE");
                setBusRoute("");
                setBusDate("");
                setMaxPrice("");
                setBasePrice("");
                setBusTime("");
                setTotalSeats("");

                // Optimistic update: add new bus to state instead of refetching all
                if (busRouteRes.data) {
                    setAllBuses(prev => [...prev, busRouteRes.data]);
                }

                if (busRouteRes.data && busRouteRes.data.id) {
                    setActiveTab('seats');
                    setSeatBusId(busRouteRes.data.id);
                    setSelectedBusForPreview(busRouteRes.data);
                } else {
                    setActiveTab('list');
                }
            } else {
                if (busRouteRes && busRouteRes.status === 401) {
                    toast.error("Session timeout. Login again!");
                    navigate("/admin/login");
                } else {
                    const err = busRouteRes ? await busRouteRes.json().catch(() => ({})) : {};
                    toast.error(err.message || "Error while creating new bus. Please Retry!");
                }
            }
        } catch (error) {
            console.error("Error creating bus:", error);
            toast.error("Failed to create bus");
        } finally {
            setIsCreatingBus(false);
        }
    }

    async function createNewSeat() {
        if (!seatNumber || !seatBusId || !seatPrice) {
            toast.error("Seat Number, Bus ID, and Price are required!");
            return;
        }

        const seatNumTrim = String(seatNumber).trim();

        // Parse and validate bus ID
        const busIdNumber = parseInt(seatBusId, 10);
        if (isNaN(busIdNumber) || !seatBusId || seatBusId === "") {
            toast.error("Please select a valid bus from the dropdown.");
            console.error('Invalid bus ID:', seatBusId);
            return;
        }

        const targetBus = allBuses.find((b) => String(b.id) === String(seatBusId));
        if (!targetBus) {
            toast.error("Selected bus not found. Please refresh and try again.");
            return;
        }

        const existingSeats = Array.isArray(targetBus.seats) ? targetBus.seats : [];
        const duplicate = existingSeats.some((s) => String(s.seatNumber).toLowerCase() === seatNumTrim.toLowerCase());
        if (duplicate) {
            toast.error("A seat with this number already exists for the selected bus.");
            return;
        }

        try {
            setIsCreatingSeat(true);
            const payload = {
                busId: busIdNumber,
                busName: targetBus?.busName || '',
                seatNumber: seatNumTrim,
                price: parseFloat(seatPrice),
                status: isReserved ? 'BOOKED' : 'AVAILABLE',
                reserved: isReserved,
                holdExpiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString() // 15 min from now
            };

            console.log('Creating seat with payload:', payload);
            const seatRes = await ApiService.post(API_CONFIG.ENDPOINTS.ADD_SEAT, payload);

            if (seatRes && (seatRes.statusCode === 200 || seatRes.statusCode === 201)) {
                toast.success("New Seat added!");
                setSeatNumber("");
                setSeatPrice("");
                setIsReserved(false);
                getAllBuses();
                // Update preview if viewing this bus
                if (selectedBusForPreview && String(selectedBusForPreview.id) === String(seatBusId)) {
                    const updatedBus = allBuses.find(b => String(b.id) === String(seatBusId));
                    if (updatedBus) setSelectedBusForPreview(updatedBus);
                }
            } else {
                toast.error(seatRes?.message || "Error while creating new seat. Please Retry!");
            }
        } catch (error) {
            console.error("Error creating seat:", error);
            toast.error("Failed to create seat");
        } finally {
            setIsCreatingSeat(false);
        }
    }

    // Filter buses
    const filteredBuses = allBuses.filter(bus => {
        if (statusFilter !== 'all') {
            const hasSeats = Array.isArray(bus.seats) && bus.seats.length > 0;
            if (statusFilter === 'active' && !hasSeats) return false;
            if (statusFilter === 'empty' && hasSeats) return false;
        }
        if (dateFilter && bus.date !== dateFilter) return false;
        return true;
    });

    // Stats
    const stats = {
        total: allBuses.length,
        active: allBuses.filter(b => Array.isArray(b.seats) && b.seats.length > 0).length,
        empty: allBuses.filter(b => !Array.isArray(b.seats) || b.seats.length === 0).length,
        totalSeats: allBuses.reduce((sum, b) => sum + (Array.isArray(b.seats) ? b.seats.length : 0), 0)
    };

    const busColumns = [
        { key: 'id', label: 'ID', sortable: true },
        { key: 'busName', label: 'Bus Name', sortable: true },
        {
            key: 'route',
            label: 'Route',
            sortable: false,
            render: (_, bus) => {
                const route = bus.route || bus.route12;
                return route ? (
                    <div className="flex items-center gap-2">
                        <span className="font-medium">{route.sourceBusStop?.name}</span>
                        <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                        </svg>
                        <span className="font-medium">{route.destinationBusStop?.name}</span>
                    </div>
                ) : <span className="text-gray-400">N/A</span>;
            }
        },
        {
            key: 'date',
            label: 'Date',
            sortable: true,
            render: (date, bus) => {
                const dateVal = date || bus.departureDateTime;
                return (
                    <span className="text-gray-700">{dateVal ? new Date(dateVal).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' }) : 'N/A'}</span>
                );
            }
        },
        {
            key: 'departureDateTime',
            label: 'Departure',
            sortable: true,
            render: (dt) => dt ? (
                <div className="flex items-center gap-2">
                    <div className="w-8 h-8 bg-indigo-100 rounded-lg flex items-center justify-center">
                        <svg className="w-4 h-4 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </div>
                    <span className="font-semibold text-indigo-600">{new Date(dt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                </div>
            ) : 'N/A'
        },
        {
            key: 'seats',
            label: 'Seats',
            sortable: false,
            render: (seats, bus) => (
                <button
                    onClick={() => handleViewSeats(bus)}
                    className="px-3 py-1.5 bg-gradient-to-r from-indigo-50 to-purple-50 text-indigo-700 rounded-lg text-xs font-semibold hover:from-indigo-100 hover:to-purple-100 transition-all flex items-center gap-2"
                >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                    </svg>
                    {Array.isArray(seats) ? seats.length : 0} seats
                </button>
            )
        },
        {
            key: 'basePrice',
            label: 'Price Range',
            sortable: true,
            render: (price, bus) => (
                <div className="text-sm">
                    <span className="text-emerald-600 font-semibold">Rs. {price}</span>
                    <span className="text-gray-400 mx-1">-</span>
                    <span className="text-orange-600 font-semibold">Rs. {bus.maxPrice}</span>
                </div>
            )
        }
    ];

    const tabs = [
        {
            id: 'list', label: 'All Buses', icon: (
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 10h16M4 14h16M4 18h16" />
                </svg>
            )
        },
        {
            id: 'add', label: 'Add Bus', icon: (
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                </svg>
            )
        },
        {
            id: 'seats', label: 'Manage Seats', icon: (
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                </svg>
            )
        }
    ];

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                    <h2 className="text-3xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                        Bus Management
                    </h2>
                    <p className="text-gray-600 mt-1">Manage your fleet of buses and seats</p>
                </div>
                <div className="flex items-center gap-3">
                    <button
                        onClick={() => getAllBuses()}
                        className="p-3 bg-white border border-gray-200 rounded-xl hover:bg-gray-50 transition-all"
                        title="Refresh"
                    >
                        <svg className="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                        </svg>
                    </button>
                </div>
            </div>

            {/* Stats Row */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-white p-4 rounded-2xl border border-gray-100 shadow-sm">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl flex items-center justify-center">
                            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4" />
                            </svg>
                        </div>
                        <div>
                            <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
                            <p className="text-sm text-gray-500">Total Buses</p>
                        </div>
                    </div>
                </div>
                <div className="bg-white p-4 rounded-2xl border border-gray-100 shadow-sm">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-gradient-to-br from-emerald-500 to-green-600 rounded-xl flex items-center justify-center">
                            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                        </div>
                        <div>
                            <p className="text-2xl font-bold text-gray-900">{stats.active}</p>
                            <p className="text-sm text-gray-500">With Seats</p>
                        </div>
                    </div>
                </div>
                <div className="bg-white p-4 rounded-2xl border border-gray-100 shadow-sm">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-gradient-to-br from-amber-500 to-orange-600 rounded-xl flex items-center justify-center">
                            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                            </svg>
                        </div>
                        <div>
                            <p className="text-2xl font-bold text-gray-900">{stats.empty}</p>
                            <p className="text-sm text-gray-500">No Seats</p>
                        </div>
                    </div>
                </div>
                <div className="bg-white p-4 rounded-2xl border border-gray-100 shadow-sm">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-600 rounded-xl flex items-center justify-center">
                            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
                            </svg>
                        </div>
                        <div>
                            <p className="text-2xl font-bold text-gray-900">{stats.totalSeats}</p>
                            <p className="text-sm text-gray-500">Total Seats</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Tab Navigation */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="border-b border-gray-100">
                    <nav className="flex -mb-px">
                        {tabs.map((tab) => (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id)}
                                className={`flex-1 sm:flex-none px-6 py-4 flex items-center justify-center gap-2 text-sm font-medium border-b-2 transition-all ${activeTab === tab.id
                                    ? 'border-indigo-500 text-indigo-600 bg-indigo-50/50'
                                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'
                                    }`}
                            >
                                {tab.icon}
                                <span className="hidden sm:inline">{tab.label}</span>
                            </button>
                        ))}
                    </nav>
                </div>

                <div className="p-6">
                    {/* List Tab */}
                    {activeTab === 'list' && (
                        <div className="space-y-4">
                            {/* Filters */}
                            <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between">
                                <div className="flex flex-wrap gap-2">
                                    {['all', 'active', 'empty'].map((status) => (
                                        <button
                                            key={status}
                                            onClick={() => setStatusFilter(status)}
                                            className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${statusFilter === status
                                                ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-500/30'
                                                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                                                }`}
                                        >
                                            {status === 'all' && `All (${stats.total})`}
                                            {status === 'active' && `With Seats (${stats.active})`}
                                            {status === 'empty' && `No Seats (${stats.empty})`}
                                        </button>
                                    ))}
                                </div>
                                <div className="flex items-center gap-3">
                                    <input
                                        type="date"
                                        value={dateFilter}
                                        onChange={(e) => setDateFilter(e.target.value)}
                                        className="px-4 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                    {dateFilter && (
                                        <button
                                            onClick={() => setDateFilter('')}
                                            className="p-2 text-gray-400 hover:text-gray-600"
                                        >
                                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                            </svg>
                                        </button>
                                    )}
                                </div>
                            </div>

                            {/* Data Table */}
                            <DataTable
                                columns={busColumns}
                                data={filteredBuses}
                                itemsPerPage={10}
                                searchable={true}
                                exportable={true}
                            />
                        </div>
                    )}

                    {/* Add Bus Tab */}
                    {activeTab === 'add' && (
                        <div className="max-w-2xl mx-auto">
                            <div className="text-center mb-8">
                                <div className="w-16 h-16 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
                                    <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                                    </svg>
                                </div>
                                <h3 className="text-xl font-bold text-gray-900">Create New Bus</h3>
                                <p className="text-gray-500 mt-1">Add a scheduled bus for a selected route</p>
                            </div>

                            {allRoutes.length > 0 ? (
                                <div className="space-y-6">
                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-2">Bus Name</label>
                                        <input
                                            type="text"
                                            placeholder="e.g. Deluxe Express"
                                            value={busName}
                                            onChange={(e) => setBusName(e.target.value)}
                                            className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                                        />
                                    </div>

                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-2">Bus Type</label>
                                        <select
                                            value={busType}
                                            onChange={(e) => setBusType(e.target.value)}
                                            className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent bg-white"
                                        >
                                            {['SEMI_DELUXE', 'VIP', 'DELUXE', 'STANDARD'].map((type) => (
                                                <option key={type} value={type}>
                                                    {type.replace('_', ' ')}
                                                </option>
                                            ))}
                                        </select>
                                    </div>

                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-2">Route</label>
                                        <select
                                            value={busRoute}
                                            onChange={(e) => setBusRoute(e.target.value)}
                                            className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent bg-white"
                                        >
                                            <option value="">Select Route</option>
                                            {allRoutes.map((route) => (
                                                <option key={route.id} value={route.id}>
                                                    {route.sourceBusStop.name} → {route.destinationBusStop.name}
                                                </option>
                                            ))}
                                        </select>
                                    </div>

                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-2">Date</label>
                                            <input
                                                type="date"
                                                value={busDate}
                                                onChange={(e) => setBusDate(e.target.value)}
                                                min={today}
                                                className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                                            />
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-2">Time</label>
                                            <input
                                                type="time"
                                                value={busTime}
                                                onChange={(e) => setBusTime(e.target.value)}
                                                className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                                            />
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-2">Base Price (Rs)</label>
                                            <input
                                                type="number"
                                                placeholder="e.g. 1000"
                                                value={basePrice}
                                                onChange={(e) => setBasePrice(e.target.value)}
                                                className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                                            />
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-2">Max Price (Rs)</label>
                                            <input
                                                type="number"
                                                placeholder="e.g. 1500"
                                                value={maxPrice}
                                                onChange={(e) => setMaxPrice(e.target.value)}
                                                className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                                            />
                                        </div>
                                    </div>

                                    <div>
                                        <label className="block text-sm font-medium text-gray-700 mb-2">Total Seats</label>
                                        <input
                                            type="number"
                                            placeholder="e.g. 40"
                                            value={totalSeats}
                                            onChange={(e) => setTotalSeats(e.target.value)}
                                            className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                                        />
                                    </div>

                                    <button
                                        onClick={createNewBus}
                                        disabled={isCreatingBus}
                                        className={`w-full bg-gradient-to-r from-indigo-600 to-purple-600 text-white px-6 py-4 rounded-xl transition-all font-semibold shadow-lg hover:shadow-xl hover:scale-[1.02] ${isCreatingBus ? 'opacity-80 cursor-not-allowed' : ''}`}
                                    >
                                        {isCreatingBus ? (
                                            <span className="flex items-center justify-center gap-2">
                                                <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                                                </svg>
                                                Creating Bus...
                                            </span>
                                        ) : 'Create Bus'}
                                    </button>
                                </div>
                            ) : (
                                <div className="text-center py-12 bg-gray-50 rounded-2xl border border-dashed border-gray-300">
                                    <svg className="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
                                    </svg>
                                    <p className="text-gray-500 font-medium">No routes available</p>
                                    <p className="text-gray-400 text-sm mt-1">Create a route first to add buses</p>
                                </div>
                            )}
                        </div>
                    )}

                    {/* Manage Seats Tab */}
                    {activeTab === 'seats' && (
                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                            {/* Add Seat Form */}
                            <div className="bg-gradient-to-br from-gray-50 to-gray-100/50 p-6 rounded-2xl border border-gray-200">
                                <div className="flex items-center gap-3 mb-6">
                                    <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-600 rounded-xl flex items-center justify-center">
                                        <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                                        </svg>
                                    </div>
                                    <div>
                                        <h3 className="text-lg font-bold text-gray-900">Add Seat</h3>
                                        <p className="text-sm text-gray-500">Add seats to a bus</p>
                                    </div>
                                </div>

                                {allBuses.length > 0 ? (
                                    <div className="space-y-4">
                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-2">Select Bus</label>
                                            <select
                                                value={seatBusId}
                                                onChange={(e) => {
                                                    const selectedValue = e.target.value;
                                                    console.log('Selected bus ID:', selectedValue);
                                                    setSeatBusId(selectedValue);
                                                    const bus = allBuses.find(b => String(b.id) === String(selectedValue));
                                                    setSelectedBusForPreview(bus || null);
                                                }}
                                                className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent bg-white"
                                            >
                                                <option value="">Select Bus</option>
                                                {allBuses.map((bus) => {
                                                    const route = bus.route || bus.route12;
                                                    const routeName = route ? `${route.sourceBusStop?.name} → ${route.destinationBusStop?.name}` : '';
                                                    const displayName = bus.busName || routeName || `Bus #${bus.id}`;
                                                    const dateVal = bus.date || bus.departureDateTime;
                                                    const dateStr = dateVal ? new Date(dateVal).toLocaleDateString() : '';

                                                    return (
                                                        <option key={bus.id} value={String(bus.id)}>
                                                            {displayName} {dateStr ? `(${dateStr})` : ''} - {Array.isArray(bus.seats) ? bus.seats.length : 0} seats
                                                        </option>
                                                    );
                                                })}
                                            </select>
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-2">Seat Number</label>
                                            <input
                                                type="text"
                                                placeholder="e.g. A1, B2"
                                                value={seatNumber}
                                                onChange={(e) => setSeatNumber(e.target.value)}
                                                className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                                            />
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-gray-700 mb-2">Price (Rs)</label>
                                            <input
                                                type="number"
                                                placeholder="e.g. 1200"
                                                value={seatPrice}
                                                onChange={(e) => setSeatPrice(e.target.value)}
                                                className="w-full p-4 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                                            />
                                        </div>

                                        <div className="flex items-center gap-3 p-4 bg-gray-50 rounded-xl border border-gray-100">
                                            <input
                                                type="checkbox"
                                                id="reserved"
                                                checked={isReserved}
                                                onChange={(e) => setIsReserved(e.target.checked)}
                                                className="w-5 h-5 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500"
                                            />
                                            <label htmlFor="reserved" className="text-sm font-medium text-gray-700 cursor-pointer">
                                                Mark as Reserved (Booked)
                                            </label>
                                        </div>

                                        <button
                                            onClick={createNewSeat}
                                            disabled={isCreatingSeat || !seatBusId}
                                            className={`w-full bg-gradient-to-r from-purple-600 to-pink-600 text-white px-6 py-4 rounded-xl transition-all font-semibold shadow-lg hover:shadow-xl ${isCreatingSeat || !seatBusId ? 'opacity-60 cursor-not-allowed' : 'hover:scale-[1.02]'}`}
                                        >
                                            {isCreatingSeat ? (
                                                <span className="flex items-center justify-center gap-2">
                                                    <svg className="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24">
                                                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                                                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                                                    </svg>
                                                    Adding Seat...
                                                </span>
                                            ) : 'Add Seat'}
                                        </button>
                                    </div>
                                ) : (
                                    <div className="text-center py-8 bg-white rounded-xl border border-dashed border-gray-300">
                                        <p className="text-gray-500">No buses available. Create a bus first.</p>
                                    </div>
                                )}
                            </div>

                            {/* Seat Preview */}
                            <div>
                                <div className="flex items-center gap-3 mb-4">
                                    <h3 className="text-lg font-bold text-gray-900">Seat Layout Preview</h3>
                                    {selectedBusForPreview && (() => {
                                        const bus = selectedBusForPreview;
                                        const route = bus.route || bus.route12;
                                        const routeName = route ? `${route.sourceBusStop?.name} → ${route.destinationBusStop?.name}` : '';
                                        const displayName = bus.busName || routeName || `Bus #${bus.id}`;
                                        return (
                                            <span className="px-3 py-1 bg-indigo-100 text-indigo-700 rounded-full text-sm font-medium">
                                                {displayName}
                                            </span>
                                        );
                                    })()}
                                </div>
                                <BusSeatPreview
                                    seats={selectedBusForPreview?.seats || []}
                                    showLegend={true}
                                />
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* Seat Preview Modal */}
            {selectedBusForPreview && activeTab === 'list' && (
                <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4" onClick={() => setSelectedBusForPreview(null)}>
                    <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full max-h-[90vh] overflow-auto" onClick={(e) => e.stopPropagation()}>
                        <div className="p-6 border-b border-gray-100 flex items-center justify-between">
                            <div>
                                <h3 className="text-lg font-bold text-gray-900">
                                    {(() => {
                                        const bus = selectedBusForPreview;
                                        const route = bus.route || bus.route12;
                                        const routeName = route ? `${route.sourceBusStop?.name} → ${route.destinationBusStop?.name}` : '';
                                        return bus.busName || routeName || `Bus #${bus.id}`;
                                    })()}
                                </h3>
                                <p className="text-sm text-gray-500">{selectedBusForPreview.date}</p>
                            </div>
                            <button
                                onClick={() => setSelectedBusForPreview(null)}
                                className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                            >
                                <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                        <div className="p-6">
                            {isLoadingDetails ? (
                                <div className="flex flex-col items-center justify-center py-12">
                                    <div className="w-12 h-12 border-4 border-indigo-200 border-t-indigo-600 rounded-full animate-spin mb-4"></div>
                                    <p className="text-gray-500 font-medium">Loading seat availability...</p>
                                </div>
                            ) : (
                                <BusSeatPreview
                                    seats={selectedBusForPreview.seats || []}
                                    showLegend={true}
                                />
                            )}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}