apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services/payment-service-deployment.yaml
  - services/hotel-service-deployment.yaml
  - services/bus-service-deployment.yaml
  - services/market-service-deployment.yaml
  - services/eureka-deployment.yaml
  - services/web-bff-deployment.yaml
  - services/booking-service-deployment.yaml
  - services/configmaps.yaml
  - secrets.yaml
  - services/auth-service-deployment.yaml
  - services/ingress.yaml
  - services/persistent-volumes.yaml
  - services/manual-pvs.yaml
  - services/prometheus-config.yaml
  - services/statefulsets.yaml
  - services/event-service-deployment.yaml
  - services/event-service-service.yaml

images:
  - name: event-service
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/event-service
    newTag: latest
  - name: booking-service
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/booking-service
    newTag: latest
  - name: web-bff
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/web-bff
    newTag: latest
  - name: payment-service
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/payment-service
    newTag: latest
  - name: hotel-service
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/hotel-service
    newTag: latest
  - name: auth-service
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/auth-service
    newTag: latest
  - name: bus-service
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/bus-service
    newTag: latest
  - name: market-service
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/market-service
    newTag: latest
  - name: eureka-server
    newName: 572638914672.dkr.ecr.us-east-1.amazonaws.com/eureka-server
    newTag: latest
