apiVersion: v1
kind: Secret
metadata:
  name: hotel-db-secret
  namespace: ticket-katum
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/hotel_db"
  username: "hotel_user"
  password: "HotelDB@Pass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: booking-db-secret
  namespace: ticket-katum
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/booking_db"
  username: "booking_user"
  password: "BookingDB@Pass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: bus-db-secret
  namespace: ticket-katum
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/bus_db"
  username: "bus_user"
  password: "BusDB@Pass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: ticket-katum
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/payment_db"
  username: "payment_user"
  password: "PaymentDB@Pass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: ticket-katum
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/auth_db"
  username: "auth_user"
  password: "AuthDB@Pass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: market-db-secret
  namespace: ticket-katum
type: Opaque
stringData:
  url: "jdbc:postgresql://postgres-service:5432/market_db"
  username: "market_user"
  password: "MarketDB@Pass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: ticket-katum
type: Opaque
stringData:
  password: "Redis@SecurePass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: ticket-katum
type: Opaque
stringData:
  username: "rabbitmq_admin"
  password: "RabbitMQ@Pass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: activemq-secret
  namespace: ticket-katum
type: Opaque
stringData:
  username: "activemq_admin"
  password: "ActiveMQ@Pass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ticket-katum
type: Opaque
stringData:
  secret: "dMbz7o4YE45aAyT6BUYMsO_ireJ00J96Xxbv6AQ65xb0Ajauql1fScOEP4hEb7oyBtjHfTjvkeXBfpSjE8uyoA"
---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-secret
  namespace: ticket-katum
type: Opaque
stringData:
  api-key: "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"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-gateway-secrets
  namespace: ticket-katum
type: Opaque
stringData:
  stripe-api-key: "sk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  esewa-merchant-id: "EPAYTEST"
  esewa-secret: "8gBm/:&EnhH.1/q"
  khalti-secret: "test_secret_key_xxxxxxxxxxxxxxxxxxxxxxxx"
---
apiVersion: v1
kind: Secret
metadata:
  name: eureka-secret
  namespace: ticket-katum
type: Opaque
stringData:
  username: "eureka_admin"
  password: "Eureka@SecurePass2024!"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudinary-secret
  namespace: ticket-katum
type: Opaque
stringData:
  cloud-name: "dsqubrfjp"
  api-key: "624365773875321"
  api-secret: "9P5wS1lelWdo6CubuJxzQiNTClw"