server:
  port: 9091

spring:
  profiles:
    include: kafka
  application:
    name: payment-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

esewa:
  merchant-code: EPAYTEST
  success-url: http://localhost:3000/payments/esewa/success
  failure-url: http://localhost:3000/payments/esewa/failure
  base-url: https://rc-epay.esewa.com.np/api/epay/main/v2/form
  verify-url: https://rc-epay.esewa.com.np/api/epay/transaction/status
  secret-key: "8gBm/:&EnhH.1/q"

sendgrid:
  api:
    key: ${SENDGRID_API_KEY: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}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
